name: Terraform CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:

  terraform-cd:

    name: Terraform CD
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 665612f7-84b1-4863-8607-48501595f57a
          tenant-id: 4b9cffca-07ab-4d9d-945d-df704d1808d4
          subscription-id: 32befec2-21d4-498b-a715-32aa460c0a9d

      - name: Install Checkov
        run: pip install checkov

      - name: Terraform Security Scan
        run: checkov -d .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve